[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "1.2"
thiserror = "1"
crc = "1.8"
clap = { version = "4.0", features = ["derive"] }
